### ISSUE TITLE
[bug] jsx file cannot be resolved in npm module

### ISSUE THREAD

**Issue by jsamr** [MAKARD/react-native-toastboard#9]
You need to [bundle your library with babel](https://codeburst.io/publish-your-own-npm-package-ff918698d450) or some other build tool.
The file `Toast.jsx` cannot be resolved by npm module dependency resolution algorithm, which has no support for JSX.

```bash
Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `./Toast` from `/home/jsamr/Programmation/SmurMobileClient/node_modules/reacsamr/Programmation/SmurMobileClient/node_modules/react-native-toastboard/src/components/Toast/index.js`. Indeed, none of these files
  * `/home/jsamr/Programmation/SmurMobileClient/node_modules/react-native-toastboard/src/components/Toast/Toast(.native||.android.js)`
  * `/home/jsamr/Programmation/SmurMobileClient/node_modules/react-native-toastboard/src/components/Toast/Toast/index(.native||.andrx|.tsx)`
    at ModuleResolver.resolveDependency (/home/jsamr/Programmation/SmurMobileClient/node_modules/metro/src/node-haste/DependencyGrap
    at ResolutionRequest.resolveDependency (/home/jsamr/Programmation/SmurMobileClient/node_modules/metro/src/node-haste/DependencyG
    at DependencyGraph.resolveDependency (/home/jsamr/Programmation/SmurMobileClient/node_modules/metro/src/node-haste/DependencyGra
    at Object.resolve (/home/jsamr/Programmation/SmurMobileClient/node_modules/metro/src/lib/transformHelpers.js:141:30)
    at dependencies.map.result (/home/jsamr/Programmation/SmurMobileClient/node_modules/metro/src/DeltaBundler/traverseDependencies.
    at Array.map (<anonymous>)
    at resolveDependencies (/home/jsamr/Programmation/SmurMobileClient/node_modules/metro/src/DeltaBundler/traverseDependencies.js:3
    at /home/jsamr/Programmation/SmurMobileClient/node_modules/metro/src/DeltaBundler/traverseDependencies.js:188:33
    at Generator.next (<anonymous>)
    at step (/home/jsamr/Programmation/SmurMobileClient/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:30)
 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓░░░░░ 71.1% (1609/2023), failed.

```

**Comment by MAKARD** [comment]
@jsamr Seems you use `metro` bundler.  Just configure it with `metro.config.js`:

```js
module.exports = {
    resolver: {
        sourceExts: ["js", "jsx"]
    }
};
```

I'm not using any bundling tool for more flexibility. Also it's prevent a tons of non obvious bugs.
